import os

MICROREACT_BASE_URL = os.getenv("MICROREACT_BASE_URL", "https://microreact.ugerm.dksund.dk/")
MICROREACT_ACCESS_TOKEN = os.getenv("MICROREACT_ACCESS_TOKEN", "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..d9g0x_C-DdxVkLnP.WyPqGDmGOV07W40kdebhgCGsd4av9hS29B3Wq99wbSMhot2WRT6sHQPdKy29NrDpwBOuSVwZeUhXpcXBDIFqt2iE_9x5c4kLz8GYIKJzg6M5N2olMcBEiFRARXA4BYzJFQeBTjkAHZx-0lSJws1GHw.4eXIudzDyIEFgqM55rRtSg")
USERNAME =  os.getenv("USER", "Finn")